import type { RelatedNorm } from '../shared/types.js';

export const VERIFIED_DATE = '2026-09-04';

export const NORMS: Record<string, RelatedNorm> = {
  constitucion: {
    key: 'constitucion',
    nombre: 'Constitución Política de Colombia',
    anio: '1991',
    articulo_apartado: 'Arts. 13, 15, 16, 29, 44 y 67',
    relacion: 'Marco de igualdad, intimidad, libre desarrollo, debido proceso, prevalencia de los derechos de niñas, niños y adolescentes y derecho a la educación.',
    enlace_oficial: 'https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?0=&i=4125',
    ultima_verificacion: VERIFIED_DATE,
  },
  ley115: {
    key: 'ley115',
    nombre: 'Ley General de Educación',
    numero: 'Ley 115',
    anio: '1994',
    articulo_apartado: 'Art. 87 y disposiciones sobre manual de convivencia',
    relacion: 'Da marco legal al manual de convivencia de los establecimientos educativos.',
    enlace_oficial: 'https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?115=&i=292',
    ultima_verificacion: VERIFIED_DATE,
  },
  ley1098: {
    key: 'ley1098',
    nombre: 'Código de la Infancia y la Adolescencia',
    numero: 'Ley 1098',
    anio: '2006',
    articulo_apartado: 'Arts. 26, 44 y 45',
    relacion: 'Exige debido proceso, protección integral y prohíbe sanciones crueles, humillantes o degradantes en el entorno educativo.',
    enlace_oficial: 'https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=22106',
    ultima_verificacion: VERIFIED_DATE,
  },
  ley1620: {
    key: 'ley1620',
    nombre: 'Sistema Nacional de Convivencia Escolar',
    numero: 'Ley 1620',
    anio: '2013',
    articulo_apartado: 'Arts. 17, 18, 21 y 29 y concordantes',
    relacion: 'Establece responsabilidades institucionales, la Ruta de Atención Integral y el marco de convivencia escolar.',
    enlace_oficial: 'https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=52287',
    ultima_verificacion: VERIFIED_DATE,
  },
  decreto1075: {
    key: 'decreto1075',
    nombre: 'Decreto Único Reglamentario del Sector Educación',
    numero: 'Decreto 1075',
    anio: '2015',
    articulo_apartado: 'Libro 2, Parte 3, Título 5 - convivencia escolar; compila el Decreto 1965 de 2013',
    relacion: 'Reglamenta la clasificación y protocolos de atención para situaciones Tipo I, II y III.',
    enlace_oficial: 'https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?1075=&i=77913',
    ultima_verificacion: VERIFIED_DATE,
  },
  ley1581: {
    key: 'ley1581',
    nombre: 'Régimen General de Protección de Datos Personales',
    numero: 'Ley 1581',
    anio: '2012',
    articulo_apartado: 'Arts. 4, 5, 6 y concordantes',
    relacion: 'Protege datos personales y datos sensibles, especialmente relevantes cuando se trata de niñas, niños y adolescentes.',
    enlace_oficial: 'https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=49981',
    ultima_verificacion: VERIFIED_DATE,
  },
  ley1801: {
    key: 'ley1801',
    nombre: 'Código Nacional de Seguridad y Convivencia Ciudadana',
    numero: 'Ley 1801',
    anio: '2016',
    articulo_apartado: 'Aplicación según la conducta; el Manual cita el art. 27 en supuestos específicos',
    relacion: 'Puede resultar aplicable cuando los hechos trascienden la convivencia escolar y comprometen comportamientos contrarios a la convivencia ciudadana.',
    enlace_oficial: 'https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=80538',
    ultima_verificacion: VERIFIED_DATE,
  },
  decreto459: {
    key: 'decreto459',
    nombre: 'Participación de las familias en los procesos educativos',
    numero: 'Decreto 459',
    anio: '2024',
    articulo_apartado: 'Capítulo adicionado al Decreto 1075 de 2015',
    relacion: 'Refuerza la participación corresponsable de las familias en los procesos educativos y de convivencia.',
    enlace_oficial: 'https://www1.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=237555',
    ultima_verificacion: VERIFIED_DATE,
  },
  directiva01: {
    key: 'directiva01',
    nombre: 'Orientaciones para la prevención de violencia sexual en entornos escolares',
    numero: 'Directiva 01',
    anio: '2022',
    articulo_apartado: 'Orientaciones integrales de prevención, atención, protección y reporte',
    relacion: 'Aplica de manera especial ante presuntas situaciones de violencia sexual en entornos escolares.',
    enlace_oficial: 'https://www.mineducacion.gov.co/1780/articles-400474_recurso_43.pdf',
    ultima_verificacion: VERIFIED_DATE,
  },
  guia49: {
    key: 'guia49',
    nombre: 'Guía Pedagógica No. 49 para la convivencia escolar',
    numero: 'Guía 49',
    anio: '2014',
    articulo_apartado: 'Orientaciones sobre manuales, Ruta de Atención Integral y protocolos',
    relacion: 'Aporta orientaciones pedagógicas para aplicar la Ley 1620 y el Decreto 1965 de 2013.',
    enlace_oficial: 'https://contenidos.mineducacion.gov.co/ntg/men/pdf/Guia%20No.%2049.pdf',
    ultima_verificacion: VERIFIED_DATE,
  },
};

export function selectNorms(keys: string[]): RelatedNorm[] {
  return [...new Set(keys)].map(k => NORMS[k]).filter(Boolean);
}
